
services:
  - type: web
    name: knowledge-api
    env: python
    region: oregon  # or choose a region closer to your users
    plan: free  # or 'starter', 'standard', 'plus' for production
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GROQ_API_KEY
        sync: False
      - key: GEMINI_API_KEY
        sync: False
      - key: DEBUG_MODE
        value: "false"
      - key: VERBOSE_LOGGING
        value: "false"
      - key: PORT
        value: 10000
    
